version: "3.9"
services:   
  base:
    image: ${ROS2_WS_CONTAINER_NAME}-${USE_ROS_DISTRO}-dev
    build:
      context: ../
      dockerfile: daisy/Dockerfile
      args:
        USE_ROS_DISTRO: ${USE_ROS_DISTRO}
        ROS2_WS_CONTAINER_NAME: ${ROS2_WS_CONTAINER_NAME}
      target: base

  dev:
    hostname: ${USE_ROS_DISTRO}-container
    image: ${ROS2_WS_CONTAINER_NAME}-${USE_ROS_DISTRO}-dev
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY} 
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority
      - $ROS2_WS_MOUNT:/root/$ROS2_WS_CONTAINER_NAME

  shell:
    container_name: ${ROS2_WS_CONTAINER_NAME}
    extends: dev
    command: sleep infinity

  exec:
    container_name: $ROS2_WS_CONTAINER_NAME-exec
    extends: dev
    command: ${COMMAND}

  rviz:
    extends: dev
    command: rviz2

  colcon-build:
    extends: dev
    command: colcon build