services:   
  base:
    image: ${ROS2_WS_CONTAINER_NAME}-${USE_ROS_DISTRO}
    build:
      context: ../
      dockerfile: daisy/Dockerfile
      args:
        - RUNTIME=${RUNTIME}
        - UBUNTU_VER=${UBUNTU_VER}
        - USE_ROS_DISTRO=${USE_ROS_DISTRO}
        - ROS2_WS_CONTAINER_NAME=${ROS2_WS_CONTAINER_NAME}
        - U_ID=${U_ID}
        - USERNAME=${USERNAME:-daisy}
        - PRELOAD_PATH=${PRELOAD_PATH:-src}
      target: base

  dev:
    runtime: ${RUNTIME}
    image: ${ROS2_WS_CONTAINER_NAME}-${USE_ROS_DISTRO}
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    user: ${USERNAME}
    environment:
      - DISPLAY=${DISPLAY:-}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/${USERNAME}/.Xauthority
      - $ROS2_WS_MOUNT:/home/${USERNAME}/$ROS2_WS_CONTAINER_NAME
      - /tmp:/tmp
    devices:
      - /dev:/dev

  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
      - TITLE=Webtop
      - DISPLAY=:200
    network_mode: host
    volumes:
      - /path/to/data:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped

  kasmvnc:
    runtime: ${RUNTIME}
    container_name: kasmvnc
    image: ghcr.io/linuxserver/baseimage-kasmvnc:alpine318
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=:200
    devices:
      - /dev/dri:/dev/dri

  rviz:
    container_name: rviz
    extends: dev
    command: rviz2

  debug:
    container_name: debug
    extends: dev
    command: sleep infinity

  colcon-build:
    container_name: colcon-build
    extends: dev
    command: colcon build
