name: ${ROS2_WS_CONTAINER_NAME}
services:   
  base:
    image: ${ROS2_WS_CONTAINER_NAME}-${USE_ROS_DISTRO}
    build:
      context: ../
      dockerfile: daisy/Dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - UBUNTU_VER=${UBUNTU_VER}
        - USE_ROS_DISTRO=${USE_ROS_DISTRO}
        - CUSTOM_BASE=${CUSTOM_BASE}
        - ROS2_WS_CONTAINER_NAME=${ROS2_WS_CONTAINER_NAME}
        - U_ID=${U_ID}
        - USERNAME=${USERNAME:-daisy}
        - PRELOAD_PATH=${PRELOAD_PATH:-src}
      target: base

  dev:
    image: ${ROS2_WS_CONTAINER_NAME}-${USE_ROS_DISTRO}
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    user: ${USERNAME}
    environment:
      - DISPLAY=${DISPLAY:-}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/${USERNAME}/.Xauthority
      - $ROS2_WS_MOUNT:/home/${USERNAME}/$ROS2_WS_CONTAINER_NAME
      - /tmp:/tmp
    devices:
      - /dev:/dev

  webtop:
    container_name: webtop
    image: lscr.io/linuxserver/webtop:latest
    environment:
      - DISPLAY=:200
    network_mode: host
    devices:
      - /dev/dri:/dev/dri 

  kasmvnc:
    container_name: kasmvnc
    image: lsiobase/kasmvnc:alpine321
    environment:
      - DISPLAY=:200
    network_mode: host
    devices:
      - /dev/dri:/dev/dri

  rviz:
    container_name: rviz
    extends: dev
    command: rviz2

  debug:
    container_name: ${ROS2_WS_CONTAINER_NAME}_debug
    extends: dev
    command: sleep infinity

  colcon-build:
    container_name: colcon-build
    extends: dev
    command: colcon build
